### PR TITLE
Work with .zip files

### PR DESCRIPTION
**Pull request by yeyeto2788**
@rocheio here is the pull request for working with zip files. 

Here you have the images that I will upload after this PR:

Normal mode (Comparison of regular folders)

folders

And the image below is to work with `.zip` folders

zip_folders

Notice the difference on the 1st checkbox value.

Once this PR is approved I will place the images in the following directory within the repo if you like to merge it to.

image_location

Regards.

### CODE REVIEW

**Comment by yeyeto2788** [comment]
BTW I forgot to mention that I have added also another feature which is to have the file size also on the reports, since there could be files on same subdirectories but different content so that's why I have added it.

Sorry for not mentioning it before.

Regards.

**Comment by rocheio** [comment]
@yeyeto2788 Looks good to me. If you resolve the conflicts with master I'll gladly merge it in. Thanks for the contribution!

**Comment by yeyeto2788** [comment]
@rocheio I don't have any problem to do so. The problem is that I can not resolve the conflicts since I don't have write permissions to do it. I don't eve see the conflicts :cry: 

a

Is there any way to see them?

**Comment by yeyeto2788** [comment]
@rocheio I managed to do it. My bad, I actually didn't know I could do it, 

Two last thing:
* The images are OK for you to put it on that location? I can also create a `.md` file within the `./Docs/` directory explaining a bit the module if you wish.
* Might it be feasible to add the feature/option to generate an `.html` file? Maybe it can be added with a simple layout (Simple header and a table).


P.D: Sorry for asking for so many changes out of the blue but just thinking many ways to improve this awesome project.

Regards.

**Comment by rocheio** [comment]
@yeyeto2788 👍 changes look good and thank YOU for contributing to the program. I'm really happy that you found it useful enough to add to.

I don't really have plans to maintain the program long-term though and no longer have easy access to a Windows environment. Would you want to fork the project to your own repo and continue development of future versions there? I'd be happy to link to your fork from the README here so others that need these (and future) features can find them easily.

**Comment by yeyeto2788** [comment]
@rocheio no problem. I'll then add the changes to my repo then.

I want to thank you for letting me contribute to this project.

If you need anything else do not hesitate on contacting me.

Best regards.

**Comment by rocheio** [comment]
Thanks again for keeping this application alive. Added a link to the top of the README so others will be able to find your improvements (https://github.com/rocheio/foldercompare#notable-forks). Reverted the rest of it to my latest update in 2016 for personal posterity.

**Comment by yeyeto2788** [comment]
No problem at all, actually thank you for letting me share some improvement on this awesome project.

Regards.

**Pull request closed without merging**
